# Generated by Django 5.0.3 on 2024-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('requests_date', models.DateTimeField(auto_now_add=True)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
