# Generated by Django 5.0.3 on 2024-04-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='amount',
        ),
    ]
