# Generated by Django 5.0.3 on 2024-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_tinkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='readies_date',
            field=models.DateTimeField(null=True),
        ),
    ]
