# Generated by Django 5.0.3 on 2024-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
